version: '3.8'

services:
  dante-server:
    build:
      context: .
      args:
        USERNAME: myUser      # Имя пользователя
        PASSWORD: myPassword  # Пароль (если USE_PASSWORD=true)
        USE_PASSWORD: "false" # Установите "true" для создания пользователя с паролем, "false" — без пароля
    ports:
      - "1081:1080"           # Порт публикации
    volumes:
      - ./sockd.conf:/etc/sockd.conf
    restart: unless-stopped

